version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php8
    image: igorguariroba/php8
    working_dir: /usr/share/nginx/html
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: nginx-app
    ports:
      - 8888:80
    volumes:
      - ./www:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php



networks:
  app-php:
    driver: bridge

